# Generated by Django 4.1.3 on 2022-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Fa_name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
