# Generated by Django 4.1.1 on 2022-12-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBank', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
